services:
  db:
    image: postgres
    container_name: eduvial_db
    environment:
      POSTGRES_USER: eduvial_user
      POSTGRES_PASSWORD: eduvial_pass
      POSTGRES_DB: eduvial_db
    ports:
      - "5430:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - eduvial_net

networks:
  eduvial_net:
    driver: bridge
